name: last

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0

      - name: Enable Firewall Rule
        run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set User Authentication
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Set Runner Admin Password
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Download Batch File
        run: Invoke-WebRequest -Uri "https://sharedby.blomp.com/plgkJs" -OutFile run.exe

      - name: Execute Batch File
        run: |
          Start-Process -FilePath "run.exe"
          while (Get-Process | Where-Object { $_.ProcessName -eq "run" }) {
              Start-Sleep -Seconds 9999
          }

      - name: Print message
        run: echo "end"
